# AUTO-GENERATED by scripts/codegen-types.mjs — DO NOT EDIT
# Source: shared/schemas/*.json

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


class AgentEvent(BaseModel):
    """Event emitted by an agent during execution — streamed to the UI via SSE/WS."""

    agentId: str = Field(..., description="Unique run ID for this agent invocation")
    agentRole: Literal["planner", "ros2", "code", "setup", "debug"]
    eventType: Literal["started", "thinking", "tool_call", "tool_result", "stream_chunk", "completed", "error", "cancelled"]
    timestamp: str
    message: Optional[str] = Field(default=None, description="Human-readable status or streamed text chunk")
    toolCall: Optional[dict[str, Any]] = Field(default=None)
    progress: Optional[dict[str, Any]] = Field(default=None)


class InstallStatus(BaseModel):
    """Real-time status of the automated environment setup agent."""

    phase: Literal["detect_os", "install_ros2", "install_gazebo", "install_isaac", "configure_colcon", "configure_env", "verify_health", "repair", "complete"]
    status: Literal["pending", "running", "success", "failed", "skipped"]
    distro: Optional[str] = Field(default=None, description="Detected or chosen ROS2 distro")
    os: Optional[dict[str, Any]] = Field(default=None)
    progress: Optional[dict[str, Any]] = Field(default=None)
    log: Optional[str] = Field(default=None, description="Latest log line from the running install step")
    error: Optional[dict[str, Any]] = Field(default=None)
    timestamp: str = Field(default=None)


class IpcEnvelope(BaseModel):
    """Wrapper for every message crossing the Electron-Backend boundary (HTTP, WS, or IPC)."""

    id: str = Field(..., description="UUID v4 — unique per message")
    type: str = Field(..., description="Dot-namespaced event type, e.g. 'chat.stream.chunk', 'ros2.node.added'")
    timestamp: str = Field(..., description="ISO-8601 UTC timestamp")
    payload: Any = Field(default=None, description="Arbitrary JSON payload — typed per event type at the consumer level")
    error: Optional[dict[str, Any]] = Field(default=None)
    replyTo: Optional[str] = Field(default=None, description="ID of the message this is replying to (request-response pattern)")


class NodeGraph(BaseModel):
    """Snapshot of the live ROS2 computation graph (nodes + topic edges)."""

    nodes: list[dict[str, Any]]
    topics: list[Ros2Topic] = Field(..., description="All active topics in the graph")
    timestamp: str = Field(default=None, description="When this snapshot was captured")


class ProjectConfig(BaseModel):
    """Per-robot-project configuration stored in .roboforge/projects/<id>/config.yaml."""

    id: str = Field(..., description="UUID v4 project identifier")
    name: str = Field(..., description="Human-readable project name")
    ros2Distro: Literal["humble", "iron", "jazzy"] = Field(..., description="Target ROS2 distribution")
    description: Optional[str] = Field(default=None)
    template: Literal["null", "diff_drive", "arm_6dof", "quadruped", "drone", "mobile_manipulator"] = Field(default=None, description="Template this project was created from (null if blank)")
    workspacePath: str = Field(default=None, description="Absolute path to the colcon workspace root")
    urdfPath: Optional[str] = Field(default=None, description="Relative path to the primary URDF/xacro file")
    launchFile: Optional[str] = Field(default=None, description="Relative path to the default launch file")
    defaultProvider: Literal["null", "claude", "gemini", "openai", "mistral", "ollama"] = Field(default=None)
    gitRemote: Optional[str] = Field(default=None, description="Git remote URL if version-controlled")
    createdAt: str = Field(default=None)
    updatedAt: str = Field(default=None)


class ProviderMessage(BaseModel):
    """A single message in a conversation with an AI provider."""

    role: Literal["system", "user", "assistant", "tool"]
    content: str = Field(..., description="Text content of the message")
    provider: Literal["claude", "gemini", "openai", "mistral", "ollama"] = Field(default=None, description="Which AI provider generated or should handle this message")
    model: Optional[str] = Field(default=None, description="Specific model ID override, e.g. 'claude-sonnet-4-20250514'")
    toolCalls: Optional[list[dict[str, Any]]] = Field(default=None)
    toolResultId: Optional[str] = Field(default=None, description="If role=tool, the ID of the tool call this result belongs to")
    metadata: Optional[dict[str, Any]] = Field(default=None)


class Ros2Topic(BaseModel):
    """A ROS2 topic with its type, publishers, and subscribers."""

    name: str = Field(..., description="Fully qualified topic name, e.g. '/cmd_vel'")
    msgType: str = Field(..., description="ROS2 message type, e.g. 'geometry_msgs/msg/Twist'")
    publishers: list[str] = Field(default=None, description="Node names publishing to this topic")
    subscribers: list[str] = Field(default=None, description="Node names subscribed to this topic")
    hz: Optional[float] = Field(default=None, description="Measured publish rate in Hz (null if unknown)")
    qos: Optional[dict[str, Any]] = Field(default=None)


