// AUTO-GENERATED by scripts/codegen-types.mjs — DO NOT EDIT
// Source: shared/schemas/*.json

/** Event emitted by an agent during execution — streamed to the UI via SSE/WS. */
export interface AgentEvent {
  agentId: string; /** Unique run ID for this agent invocation */
  agentRole: "planner" | "ros2" | "code" | "setup" | "debug";
  eventType: "started" | "thinking" | "tool_call" | "tool_result" | "stream_chunk" | "completed" | "error" | "cancelled";
  timestamp: string;
  message?: string | null; /** Human-readable status or streamed text chunk */
  toolCall?: { name: string; arguments: Record<string, unknown>; result: unknown } | null;
  progress?: { step: number; totalSteps: number; label: string } | null;
}

/** Real-time status of the automated environment setup agent. */
export interface InstallStatus {
  phase: "detect_os" | "install_ros2" | "install_gazebo" | "install_isaac" | "configure_colcon" | "configure_env" | "verify_health" | "repair" | "complete";
  status: "pending" | "running" | "success" | "failed" | "skipped";
  distro?: string | null; /** Detected or chosen ROS2 distro */
  os?: { name: string; version: string; arch: string; wsl: boolean } | null;
  progress?: { percent: number; step: number; totalSteps: number; label: string } | null;
  log?: string | null; /** Latest log line from the running install step */
  error?: { code: string; message: string; recoverable: boolean } | null;
  timestamp?: string;
}

/** Wrapper for every message crossing the Electron-Backend boundary (HTTP, WS, or IPC). */
export interface IpcEnvelope {
  id: string; /** UUID v4 — unique per message */
  type: string; /** Dot-namespaced event type, e.g. 'chat.stream.chunk', 'ros2.node.added' */
  timestamp: string; /** ISO-8601 UTC timestamp */
  payload?: unknown; /** Arbitrary JSON payload — typed per event type at the consumer level */
  error?: { code: string; message: string; details: unknown } | null;
  replyTo?: string | null; /** ID of the message this is replying to (request-response pattern) */
}

/** Snapshot of the live ROS2 computation graph (nodes + topic edges). */
export interface NodeGraph {
  nodes: { name: string; namespace: string; package: string | null; executable: string | null; pid: number | null; publishers: string[]; subscribers: string[]; services: string[]; parameters: string[] }[];
  topics: Ros2Topic[]; /** All active topics in the graph */
  timestamp?: string; /** When this snapshot was captured */
}

/** Per-robot-project configuration stored in .roboforge/projects/<id>/config.yaml. */
export interface ProjectConfig {
  id: string; /** UUID v4 project identifier */
  name: string; /** Human-readable project name */
  description?: string | null;
  template?: "null" | "diff_drive" | "arm_6dof" | "quadruped" | "drone" | "mobile_manipulator"; /** Template this project was created from (null if blank) */
  ros2Distro: "humble" | "iron" | "jazzy"; /** Target ROS2 distribution */
  workspacePath?: string; /** Absolute path to the colcon workspace root */
  urdfPath?: string | null; /** Relative path to the primary URDF/xacro file */
  launchFile?: string | null; /** Relative path to the default launch file */
  defaultProvider?: "null" | "claude" | "gemini" | "openai" | "mistral" | "ollama";
  gitRemote?: string | null; /** Git remote URL if version-controlled */
  createdAt?: string;
  updatedAt?: string;
}

/** A single message in a conversation with an AI provider. */
export interface ProviderMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string; /** Text content of the message */
  provider?: "claude" | "gemini" | "openai" | "mistral" | "ollama"; /** Which AI provider generated or should handle this message */
  model?: string | null; /** Specific model ID override, e.g. 'claude-sonnet-4-20250514' */
  toolCalls?: { id: string; name: string; arguments: Record<string, unknown> }[] | null;
  toolResultId?: string | null; /** If role=tool, the ID of the tool call this result belongs to */
  metadata?: { tokens: number; latencyMs: number; finishReason: string } | null;
}

/** A ROS2 topic with its type, publishers, and subscribers. */
export interface Ros2Topic {
  name: string; /** Fully qualified topic name, e.g. '/cmd_vel' */
  msgType: string; /** ROS2 message type, e.g. 'geometry_msgs/msg/Twist' */
  publishers?: string[]; /** Node names publishing to this topic */
  subscribers?: string[]; /** Node names subscribed to this topic */
  hz?: number | null; /** Measured publish rate in Hz (null if unknown) */
  qos?: { reliability: "reliable" | "best_effort"; durability: "transient_local" | "volatile"; depth: number } | null;
}

