/**
 * codegen-types.mjs — Reads JSON Schemas from shared/schemas/ and generates:
 *   1. shared/ts/index.ts  — TypeScript interfaces
 *   2. shared/py/__init__.py — Pydantic v2 models
 *
 * Run: node scripts/codegen-types.mjs
 *
 * Zero external deps — uses only Node built-ins.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMAS_DIR = join(__dirname, "..", "shared", "schemas");
const TS_OUT = join(__dirname, "..", "shared", "ts", "index.ts");
const PY_OUT = join(__dirname, "..", "shared", "py", "__init__.py");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function pascalCase(s) {
  return s
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

// ---------------------------------------------------------------------------
// JSON Schema type -> TypeScript type
// ---------------------------------------------------------------------------

function jsonTypeToTs(prop) {
  if (prop.$ref) return pascalCase(prop.$ref);
  if (prop.enum) return prop.enum.map((v) => `"${v}"`).join(" | ");

  const raw = prop.type;
  if (!raw) return "unknown";

  if (Array.isArray(raw)) {
    return raw.map((t) => (t === "null" ? "null" : jsonScalarToTs(t, prop))).join(" | ");
  }
  return jsonScalarToTs(raw, prop);
}

function jsonScalarToTs(t, prop) {
  switch (t) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      if (prop.items) {
        if (prop.items.$ref) return `${pascalCase(prop.items.$ref)}[]`;
        return `${jsonTypeToTs(prop.items)}[]`;
      }
      return "unknown[]";
    case "object":
      if (prop.properties) {
        const inner = Object.entries(prop.properties)
          .map(([k, v]) => `${k}: ${jsonTypeToTs(v)}`)
          .join("; ");
        return `{ ${inner} }`;
      }
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

// ---------------------------------------------------------------------------
// JSON Schema type -> Python type
// ---------------------------------------------------------------------------

function jsonTypeToPy(prop) {
  if (prop.$ref) return pascalCase(prop.$ref);
  if (prop.enum) return `Literal[${prop.enum.map((v) => `"${v}"`).join(", ")}]`;

  const raw = prop.type;
  if (!raw) return "Any";

  if (Array.isArray(raw)) {
    const types = raw.filter((t) => t !== "null").map((t) => jsonScalarToPy(t, prop));
    return `Optional[${types.join(" | ")}]`;
  }
  return jsonScalarToPy(raw, prop);
}

function jsonScalarToPy(t, prop) {
  switch (t) {
    case "string":
      return "str";
    case "integer":
      return "int";
    case "number":
      return "float";
    case "boolean":
      return "bool";
    case "array":
      if (prop.items) {
        if (prop.items.$ref) return `list[${pascalCase(prop.items.$ref)}]`;
        return `list[${jsonTypeToPy(prop.items)}]`;
      }
      return "list[Any]";
    case "object":
      return "dict[str, Any]";
    default:
      return "Any";
  }
}

// ---------------------------------------------------------------------------
// Load schemas
// ---------------------------------------------------------------------------

const schemaFiles = readdirSync(SCHEMAS_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

const schemas = schemaFiles.map((f) =>
  JSON.parse(readFileSync(join(SCHEMAS_DIR, f), "utf-8"))
);

// ---------------------------------------------------------------------------
// Generate TypeScript
// ---------------------------------------------------------------------------

let ts = `// AUTO-GENERATED by scripts/codegen-types.mjs — DO NOT EDIT\n`;
ts += `// Source: shared/schemas/*.json\n\n`;

for (const schema of schemas) {
  const name = schema.title;
  const required = new Set(schema.required ?? []);
  ts += `/** ${schema.description ?? name} */\n`;
  ts += `export interface ${name} {\n`;

  for (const [key, prop] of Object.entries(schema.properties ?? {})) {
    const opt = required.has(key) ? "" : "?";
    const desc = prop.description ? ` /** ${prop.description} */` : "";
    ts += `  ${key}${opt}: ${jsonTypeToTs(prop)};${desc}\n`;
  }

  ts += `}\n\n`;
}

mkdirSync(join(__dirname, "..", "shared", "ts"), { recursive: true });
writeFileSync(TS_OUT, ts, "utf-8");
console.log(`OK  Generated ${TS_OUT} (${schemas.length} types)`);

// ---------------------------------------------------------------------------
// Generate Pydantic
// ---------------------------------------------------------------------------

let py = `# AUTO-GENERATED by scripts/codegen-types.mjs — DO NOT EDIT\n`;
py += `# Source: shared/schemas/*.json\n\n`;
py += `from __future__ import annotations\n\n`;
py += `from datetime import datetime\n`;
py += `from typing import Any, Literal, Optional\n\n`;
py += `from pydantic import BaseModel, Field\n\n\n`;

for (const schema of schemas) {
  const name = schema.title;
  const required = new Set(schema.required ?? []);
  py += `class ${name}(BaseModel):\n`;
  py += `    """${schema.description ?? name}"""\n\n`;

  const props = Object.entries(schema.properties ?? {});
  if (props.length === 0) {
    py += `    pass\n\n\n`;
    continue;
  }

  // Required fields first, then optional
  const sortedProps = [...props].sort(([aKey], [bKey]) => {
    const aReq = required.has(aKey) ? 0 : 1;
    const bReq = required.has(bKey) ? 0 : 1;
    return aReq - bReq;
  });

  for (const [key, prop] of sortedProps) {
    const pyType = jsonTypeToPy(prop);
    const desc = prop.description ? `, description="${prop.description}"` : "";

    if (required.has(key)) {
      if (desc) {
        py += `    ${key}: ${pyType} = Field(...${desc})\n`;
      } else {
        py += `    ${key}: ${pyType}\n`;
      }
    } else {
      py += `    ${key}: ${pyType} = Field(default=None${desc})\n`;
    }
  }

  py += `\n\n`;
}

mkdirSync(join(__dirname, "..", "shared", "py"), { recursive: true });
writeFileSync(PY_OUT, py, "utf-8");
console.log(`OK  Generated ${PY_OUT} (${schemas.length} models)`);
